{% set version = '2.2-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spam
  version: {{ version|replace("-", "_") }}

source:
  fn: spam_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/spam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spam/spam_{{ version }}.tar.gz
  sha256: a18564b6930c10c2f5d1002414d6ec6ab335d57a29013f7ecd6d18e16a43670b

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dotcall64
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dotcall64

test:
  commands:
    - $R -e "library('spam')"           # [not win]
    - "\"%R%\" -e \"library('spam')\""  # [win]

about:
  home: https://git.math.uzh.ch/reinhard.furrer/spam
  license: LGPL-2 | BSD_3_clause
  summary: 'Set of functions for sparse matrix algebra. Differences with other sparse matrix
    packages are: (1) we only support (essentially) one sparse matrix format, (2) based
    on transparent and simple structure(s), (3) tailored for MCMC calculations within
    G(M)RF. (4) and it is fast and scalable (with the extension package spam64).'
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
