{% set version = "2.11-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spam
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spam/spam_{{ version }}.tar.gz
  sha256: d849a6c06dd41598d97518dfb476ae6eacb7ecef810c8e0cb2b355ffad335d09

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-dotcall64                      # [build_platform != target_platform]
    - r-rcpp >=1.0.8.3                 # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-dotcall64
    - r-rcpp >=1.0.8.3
  run:
    - r-base
    - r-dotcall64
    - r-rcpp >=1.0.8.3

test:
  commands:
    - $R -e "library('spam')"           # [not win]
    - "\"%R%\" -e \"library('spam')\""  # [win]

about:
  home: https://www.math.uzh.ch/pages/spam/
  license: LGPL-2.0-only OR BSD-3-Clause
  summary: "Set of functions for sparse matrix algebra. Differences with other sparse matrix packages are: (1) we only support (essentially) one sparse matrix format, (2) based on transparent and simple structure(s), (3) tailored for MCMC calculations within G(M)RF. (4) and it is fast and scalable (with the extension package
    spam64). Documentation about 'spam' is provided by vignettes included in this package, see also Furrer and Sain (2010) <doi:10.18637/jss.v036.i10>; see 'citation(\"spam\")' for details."
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
