travis:
  secure:
    BINSTAR_TOKEN: OBUFKBR8H6Yp2ulzqG7KJx/I9arQdMBAybdTVGdLET9sNuYeAji4VYsxk/khbJCPm6LVZuADjcTNNpKpzr92mSxaOCvRs9noFafPFUke3IW3aiciB5GtJebRugicqzVCT6NGJFfWNqZwzGPlEPRODPd0UyQET6/yeSeRD+CfC4Uvk8CtpjfcQVR5JK1Cpl8D/392RRSvRDLfnYg+Ok9jJyWEaXYNGnaXSGlDj4hBu3ymmA+c9AxctS2hn6YYYGuKDYeoAeryCnVVk7g9GPioFDfJoWNK7UOFvk6PU3P/il7+o3ckDH4eXIm9IGOMDzlZrQ48UgGpVV7OZqnlN7DgcYXFaphemTdsGBzUG9H84Jb0vyc1KE6SNItCAX9TprQpJA5le02bFYqRJ5WbCY6sKAFTbGtvDhhXVvVHee4qitlEbEvgB4GSlBTUTpO1bL/oHob+SkRDNy+yj2KNtfgWsY1nqePpt9OcFlE1frmlHWHo0N67aNBa7/in9iNB/rLmo6DiPgPNeRkuDkst8EUH4KiQH3QZBc+tzmvc8RWRNkDF2NAz+NB1vPrBU8c3wY3pxywyx5QhuPuZGf94PDQbre0df9sS9oXO7k9yVi3tvRj8aBjDB3afeC1ic37qyc4uzrrr7rwk8tDn60QdSRcVYcT0N9oaALUGjri1Aw2RbDU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
