appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gADPdxjLaP42Mc253UbQY3XyrfXBBsLx1qNb6v0ea9HEvFz/nv6KMni7G4KBtU7ETiJQBlEWHG98MVMGUbT1RfnEqO7S29lNmvHKstfHlcc7Iq2CqmHxdOgJrxs+fTzbNjzQRgRDAp1YdyRMTbRvHBLKg1pQpdaL5KF8E462eEo1u9iLAXpZuf2tWxCD+BvmmGyC/mj1yenBQ3XdtsnhzOzAQYdhSWxj/ppcvWfl5oVcbm3uDg8i/yDPx52F7ivk7dLlBXK3mDbMDtP9DKK1lb7EHOJ5L0gDKaGRetiscm21Y0uYVfEpCuqCFB+Hbcj1Fz8JR33IAICrk6lA1HYYyGFyQaKLKaQGOk2epL/vWJiD/ZV/0B29Cx2f38IUXbBsVI64q3PcMHG+dsbM8c/CzUb2/0/1+ycZpLcJaSaPCyYTTcz7tUROZR5NutXKASF5aIDasEyatmjoHKXioK8Hkqny6djHVfU5ILJUHdQrkuXrnnKilmhWRAmUyfN05NJqi/UBJe0J+8RfDLVYYUksACAF/pV8alfFUimQGByfuS5FkXtk/l2E8CWEJTb1a2cX0GqEzZIccgCTdZivZaw/BRd7CW+EgPdKjNmg1Uui6vjgZG9uYi5X5pREjlSeMSx/glxbDNvEd1nZWVc3XJee+G5GG7AMYM4QrKXcEIhfszw=}
